name: hockey_math
description: A Flutter app that helps hockey families find the best time to leave for games.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  url_launcher: ^6.2.5
  add_2_calendar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/HockeyMathLogo.png 